[package]
name = "vedic-wasm"
version = "2.0.6"
authors = ["Pt. Prashant Tripathi <ptprashanttripathi@outlook.com>"]
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
vedic-core = { path = "../core" }
wasm-bindgen = "0.2.37"

